# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1127e76c977bbb8ff1619655182cd8dd2b8f96926646e39cd81d3507163d1532324401bf286a686765586f7a834bc76d78f7b9aa0fa365cf1c182aa5aea22c66

test:
  secret_key_base: 531918a15c2d67c2953829c5eee4b735a95fdca680737590c80cd7913c86cfe94bb4eafb604bf788928c92d53c2f1586215f43ab410068bf58daea7043c78966

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
